/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { OneButtonGame } from './OneButtonGame.js';
export * as factories from './factories/index.js';
export { OneButtonGame__factory } from './factories/OneButtonGame__factory.js';