/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface OneButtonGameInterface extends Interface {
    getFunction(nameOrSignature: "BASE_COST" | "BPS_DENOMINATOR" | "COST_MULTIPLIER_BPS" | "DIVIDEND_BPS" | "SAME_WALLET_COOLDOWN" | "SEASON_DURATION" | "TREASURY_BPS" | "WINNER_BPS" | "claimDividend" | "currentRoundId" | "currentSeasonId" | "dividendClaimed" | "fullResetDuration" | "getCurrentPhase" | "getCurrentPressCost" | "getPressCost" | "getTimeRemaining" | "latePhaseExtension" | "latePhaseThreshold" | "owner" | "pause" | "paused" | "playerContribution" | "playerLastPressAt" | "playerPressCount" | "press" | "renounceOwnership" | "rollRoundIfExpiredWithoutPresses" | "roundHasParticipated" | "rounds" | "seasons" | "setTimingConfig" | "setTreasury" | "settleRound" | "suddenDeathExtension" | "suddenDeathThreshold" | "transferOwnership" | "treasury" | "unpause"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ButtonPressed" | "DividendClaimed" | "OwnershipTransferred" | "Paused" | "RoundRolledWithoutPresses" | "RoundSettled" | "RoundStarted" | "SeasonFinalized" | "SeasonStarted" | "TimingConfigUpdated" | "TreasuryUpdated" | "Unpaused"): EventFragment;

    encodeFunctionData(functionFragment: 'BASE_COST', values?: undefined): string;
encodeFunctionData(functionFragment: 'BPS_DENOMINATOR', values?: undefined): string;
encodeFunctionData(functionFragment: 'COST_MULTIPLIER_BPS', values?: undefined): string;
encodeFunctionData(functionFragment: 'DIVIDEND_BPS', values?: undefined): string;
encodeFunctionData(functionFragment: 'SAME_WALLET_COOLDOWN', values?: undefined): string;
encodeFunctionData(functionFragment: 'SEASON_DURATION', values?: undefined): string;
encodeFunctionData(functionFragment: 'TREASURY_BPS', values?: undefined): string;
encodeFunctionData(functionFragment: 'WINNER_BPS', values?: undefined): string;
encodeFunctionData(functionFragment: 'claimDividend', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'currentRoundId', values?: undefined): string;
encodeFunctionData(functionFragment: 'currentSeasonId', values?: undefined): string;
encodeFunctionData(functionFragment: 'dividendClaimed', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'fullResetDuration', values?: undefined): string;
encodeFunctionData(functionFragment: 'getCurrentPhase', values?: undefined): string;
encodeFunctionData(functionFragment: 'getCurrentPressCost', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getPressCost', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'getTimeRemaining', values?: undefined): string;
encodeFunctionData(functionFragment: 'latePhaseExtension', values?: undefined): string;
encodeFunctionData(functionFragment: 'latePhaseThreshold', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'pause', values?: undefined): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'playerContribution', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'playerLastPressAt', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'playerPressCount', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'press', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'rollRoundIfExpiredWithoutPresses', values?: undefined): string;
encodeFunctionData(functionFragment: 'roundHasParticipated', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'rounds', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'seasons', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setTimingConfig', values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'setTreasury', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'settleRound', values?: undefined): string;
encodeFunctionData(functionFragment: 'suddenDeathExtension', values?: undefined): string;
encodeFunctionData(functionFragment: 'suddenDeathThreshold', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'treasury', values?: undefined): string;
encodeFunctionData(functionFragment: 'unpause', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'BASE_COST', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'BPS_DENOMINATOR', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'COST_MULTIPLIER_BPS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'DIVIDEND_BPS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'SAME_WALLET_COOLDOWN', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'SEASON_DURATION', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'TREASURY_BPS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'WINNER_BPS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimDividend', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'currentRoundId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'currentSeasonId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'dividendClaimed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fullResetDuration', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCurrentPhase', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getCurrentPressCost', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPressCost', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTimeRemaining', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'latePhaseExtension', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'latePhaseThreshold', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'playerContribution', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'playerLastPressAt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'playerPressCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'press', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rollRoundIfExpiredWithoutPresses', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'roundHasParticipated', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rounds', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'seasons', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTimingConfig', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTreasury', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'settleRound', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'suddenDeathExtension', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'suddenDeathThreshold', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'treasury', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unpause', data: BytesLike): Result;
  }

  
    export namespace ButtonPressedEvent {
      export type InputTuple = [roundId: BigNumberish, seasonId: BigNumberish, player: AddressLike, pressCountForPlayer: BigNumberish, amountPaid: BigNumberish, totalPot: BigNumberish, previousEndTime: BigNumberish, newEndTime: BigNumberish, newLeader: AddressLike];
      export type OutputTuple = [roundId: bigint, seasonId: bigint, player: string, pressCountForPlayer: bigint, amountPaid: bigint, totalPot: bigint, previousEndTime: bigint, newEndTime: bigint, newLeader: string];
      export interface OutputObject {roundId: bigint, seasonId: bigint, player: string, pressCountForPlayer: bigint, amountPaid: bigint, totalPot: bigint, previousEndTime: bigint, newEndTime: bigint, newLeader: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DividendClaimedEvent {
      export type InputTuple = [roundId: BigNumberish, player: AddressLike, amount: BigNumberish];
      export type OutputTuple = [roundId: bigint, player: string, amount: bigint];
      export interface OutputObject {roundId: bigint, player: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoundRolledWithoutPressesEvent {
      export type InputTuple = [expiredRoundId: BigNumberish, newRoundId: BigNumberish, seasonId: BigNumberish];
      export type OutputTuple = [expiredRoundId: bigint, newRoundId: bigint, seasonId: bigint];
      export interface OutputObject {expiredRoundId: bigint, newRoundId: bigint, seasonId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoundSettledEvent {
      export type InputTuple = [roundId: BigNumberish, seasonId: BigNumberish, winner: AddressLike, totalPot: BigNumberish, winnerPayout: BigNumberish, dividendPool: BigNumberish, treasuryAmount: BigNumberish, settledAt: BigNumberish];
      export type OutputTuple = [roundId: bigint, seasonId: bigint, winner: string, totalPot: bigint, winnerPayout: bigint, dividendPool: bigint, treasuryAmount: bigint, settledAt: bigint];
      export interface OutputObject {roundId: bigint, seasonId: bigint, winner: string, totalPot: bigint, winnerPayout: bigint, dividendPool: bigint, treasuryAmount: bigint, settledAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoundStartedEvent {
      export type InputTuple = [roundId: BigNumberish, seasonId: BigNumberish, startTime: BigNumberish, endTime: BigNumberish];
      export type OutputTuple = [roundId: bigint, seasonId: bigint, startTime: bigint, endTime: bigint];
      export interface OutputObject {roundId: bigint, seasonId: bigint, startTime: bigint, endTime: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SeasonFinalizedEvent {
      export type InputTuple = [seasonId: BigNumberish, totalRounds: BigNumberish, totalPot: BigNumberish, totalPresses: BigNumberish];
      export type OutputTuple = [seasonId: bigint, totalRounds: bigint, totalPot: bigint, totalPresses: bigint];
      export interface OutputObject {seasonId: bigint, totalRounds: bigint, totalPot: bigint, totalPresses: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SeasonStartedEvent {
      export type InputTuple = [seasonId: BigNumberish, startTime: BigNumberish, endTime: BigNumberish];
      export type OutputTuple = [seasonId: bigint, startTime: bigint, endTime: bigint];
      export interface OutputObject {seasonId: bigint, startTime: bigint, endTime: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TimingConfigUpdatedEvent {
      export type InputTuple = [fullResetDuration: BigNumberish, latePhaseThreshold: BigNumberish, suddenDeathThreshold: BigNumberish, latePhaseExtension: BigNumberish, suddenDeathExtension: BigNumberish];
      export type OutputTuple = [fullResetDuration: bigint, latePhaseThreshold: bigint, suddenDeathThreshold: bigint, latePhaseExtension: bigint, suddenDeathExtension: bigint];
      export interface OutputObject {fullResetDuration: bigint, latePhaseThreshold: bigint, suddenDeathThreshold: bigint, latePhaseExtension: bigint, suddenDeathExtension: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TreasuryUpdatedEvent {
      export type InputTuple = [oldTreasury: AddressLike, newTreasury: AddressLike];
      export type OutputTuple = [oldTreasury: string, newTreasury: string];
      export interface OutputObject {oldTreasury: string, newTreasury: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnpausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface OneButtonGame extends BaseContract {
    
    connect(runner?: ContractRunner | null): OneButtonGame;
    waitForDeployment(): Promise<this>;

    interface: OneButtonGameInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    BASE_COST: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    BPS_DENOMINATOR: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    COST_MULTIPLIER_BPS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    DIVIDEND_BPS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    SAME_WALLET_COOLDOWN: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    SEASON_DURATION: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    TREASURY_BPS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    WINNER_BPS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    claimDividend: TypedContractMethod<
      [roundId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    currentRoundId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    currentSeasonId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    dividendClaimed: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    fullResetDuration: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getCurrentPhase: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getCurrentPressCost: TypedContractMethod<
      [player: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getPressCost: TypedContractMethod<
      [roundId: BigNumberish, player: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getTimeRemaining: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    latePhaseExtension: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    latePhaseThreshold: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    playerContribution: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    playerLastPressAt: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    playerPressCount: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    press: TypedContractMethod<
      [],
      [void],
      'payable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    rollRoundIfExpiredWithoutPresses: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    roundHasParticipated: TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    rounds: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, string, boolean] & {id: bigint, seasonId: bigint, startTime: bigint, endTime: bigint, totalPot: bigint, winnerPayout: bigint, dividendPool: bigint, treasuryAmount: bigint, totalPresses: bigint, uniquePlayers: bigint, lastPresser: string, settled: boolean }],
      'view'
    >
    

    
    seasons: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, boolean] & {id: bigint, startTime: bigint, endTime: bigint, totalRounds: bigint, totalPot: bigint, totalWinnerPayouts: bigint, totalDividendPools: bigint, totalTreasuryAmount: bigint, totalPresses: bigint, totalUniquePlayers: bigint, finalized: boolean }],
      'view'
    >
    

    
    setTimingConfig: TypedContractMethod<
      [newFullResetDuration: BigNumberish, newLatePhaseThreshold: BigNumberish, newSuddenDeathThreshold: BigNumberish, newLatePhaseExtension: BigNumberish, newSuddenDeathExtension: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setTreasury: TypedContractMethod<
      [newTreasury: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    settleRound: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    suddenDeathExtension: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    suddenDeathThreshold: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    treasury: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    unpause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'BASE_COST'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'BPS_DENOMINATOR'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'COST_MULTIPLIER_BPS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'DIVIDEND_BPS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'SAME_WALLET_COOLDOWN'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'SEASON_DURATION'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'TREASURY_BPS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'WINNER_BPS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'claimDividend'): TypedContractMethod<
      [roundId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'currentRoundId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'currentSeasonId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'dividendClaimed'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'fullResetDuration'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getCurrentPhase'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getCurrentPressCost'): TypedContractMethod<
      [player: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getPressCost'): TypedContractMethod<
      [roundId: BigNumberish, player: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getTimeRemaining'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'latePhaseExtension'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'latePhaseThreshold'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'playerContribution'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'playerLastPressAt'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'playerPressCount'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'press'): TypedContractMethod<
      [],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'rollRoundIfExpiredWithoutPresses'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'roundHasParticipated'): TypedContractMethod<
      [arg0: BigNumberish, arg1: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'rounds'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, string, boolean] & {id: bigint, seasonId: bigint, startTime: bigint, endTime: bigint, totalPot: bigint, winnerPayout: bigint, dividendPool: bigint, treasuryAmount: bigint, totalPresses: bigint, uniquePlayers: bigint, lastPresser: string, settled: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'seasons'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, bigint, boolean] & {id: bigint, startTime: bigint, endTime: bigint, totalRounds: bigint, totalPot: bigint, totalWinnerPayouts: bigint, totalDividendPools: bigint, totalTreasuryAmount: bigint, totalPresses: bigint, totalUniquePlayers: bigint, finalized: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'setTimingConfig'): TypedContractMethod<
      [newFullResetDuration: BigNumberish, newLatePhaseThreshold: BigNumberish, newSuddenDeathThreshold: BigNumberish, newLatePhaseExtension: BigNumberish, newSuddenDeathExtension: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setTreasury'): TypedContractMethod<
      [newTreasury: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'settleRound'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'suddenDeathExtension'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'suddenDeathThreshold'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'treasury'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'unpause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'ButtonPressed'): TypedContractEvent<ButtonPressedEvent.InputTuple, ButtonPressedEvent.OutputTuple, ButtonPressedEvent.OutputObject>;
getEvent(key: 'DividendClaimed'): TypedContractEvent<DividendClaimedEvent.InputTuple, DividendClaimedEvent.OutputTuple, DividendClaimedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'Paused'): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
getEvent(key: 'RoundRolledWithoutPresses'): TypedContractEvent<RoundRolledWithoutPressesEvent.InputTuple, RoundRolledWithoutPressesEvent.OutputTuple, RoundRolledWithoutPressesEvent.OutputObject>;
getEvent(key: 'RoundSettled'): TypedContractEvent<RoundSettledEvent.InputTuple, RoundSettledEvent.OutputTuple, RoundSettledEvent.OutputObject>;
getEvent(key: 'RoundStarted'): TypedContractEvent<RoundStartedEvent.InputTuple, RoundStartedEvent.OutputTuple, RoundStartedEvent.OutputObject>;
getEvent(key: 'SeasonFinalized'): TypedContractEvent<SeasonFinalizedEvent.InputTuple, SeasonFinalizedEvent.OutputTuple, SeasonFinalizedEvent.OutputObject>;
getEvent(key: 'SeasonStarted'): TypedContractEvent<SeasonStartedEvent.InputTuple, SeasonStartedEvent.OutputTuple, SeasonStartedEvent.OutputObject>;
getEvent(key: 'TimingConfigUpdated'): TypedContractEvent<TimingConfigUpdatedEvent.InputTuple, TimingConfigUpdatedEvent.OutputTuple, TimingConfigUpdatedEvent.OutputObject>;
getEvent(key: 'TreasuryUpdated'): TypedContractEvent<TreasuryUpdatedEvent.InputTuple, TreasuryUpdatedEvent.OutputTuple, TreasuryUpdatedEvent.OutputObject>;
getEvent(key: 'Unpaused'): TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;

    filters: {
      
      'ButtonPressed(uint256,uint256,address,uint32,uint256,uint256,uint64,uint64,address)': TypedContractEvent<ButtonPressedEvent.InputTuple, ButtonPressedEvent.OutputTuple, ButtonPressedEvent.OutputObject>;
      ButtonPressed: TypedContractEvent<ButtonPressedEvent.InputTuple, ButtonPressedEvent.OutputTuple, ButtonPressedEvent.OutputObject>;
    

      'DividendClaimed(uint256,address,uint256)': TypedContractEvent<DividendClaimedEvent.InputTuple, DividendClaimedEvent.OutputTuple, DividendClaimedEvent.OutputObject>;
      DividendClaimed: TypedContractEvent<DividendClaimedEvent.InputTuple, DividendClaimedEvent.OutputTuple, DividendClaimedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'Paused(address)': TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
      Paused: TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
    

      'RoundRolledWithoutPresses(uint256,uint256,uint256)': TypedContractEvent<RoundRolledWithoutPressesEvent.InputTuple, RoundRolledWithoutPressesEvent.OutputTuple, RoundRolledWithoutPressesEvent.OutputObject>;
      RoundRolledWithoutPresses: TypedContractEvent<RoundRolledWithoutPressesEvent.InputTuple, RoundRolledWithoutPressesEvent.OutputTuple, RoundRolledWithoutPressesEvent.OutputObject>;
    

      'RoundSettled(uint256,uint256,address,uint256,uint256,uint256,uint256,uint64)': TypedContractEvent<RoundSettledEvent.InputTuple, RoundSettledEvent.OutputTuple, RoundSettledEvent.OutputObject>;
      RoundSettled: TypedContractEvent<RoundSettledEvent.InputTuple, RoundSettledEvent.OutputTuple, RoundSettledEvent.OutputObject>;
    

      'RoundStarted(uint256,uint256,uint64,uint64)': TypedContractEvent<RoundStartedEvent.InputTuple, RoundStartedEvent.OutputTuple, RoundStartedEvent.OutputObject>;
      RoundStarted: TypedContractEvent<RoundStartedEvent.InputTuple, RoundStartedEvent.OutputTuple, RoundStartedEvent.OutputObject>;
    

      'SeasonFinalized(uint256,uint32,uint256,uint32)': TypedContractEvent<SeasonFinalizedEvent.InputTuple, SeasonFinalizedEvent.OutputTuple, SeasonFinalizedEvent.OutputObject>;
      SeasonFinalized: TypedContractEvent<SeasonFinalizedEvent.InputTuple, SeasonFinalizedEvent.OutputTuple, SeasonFinalizedEvent.OutputObject>;
    

      'SeasonStarted(uint256,uint64,uint64)': TypedContractEvent<SeasonStartedEvent.InputTuple, SeasonStartedEvent.OutputTuple, SeasonStartedEvent.OutputObject>;
      SeasonStarted: TypedContractEvent<SeasonStartedEvent.InputTuple, SeasonStartedEvent.OutputTuple, SeasonStartedEvent.OutputObject>;
    

      'TimingConfigUpdated(uint256,uint256,uint256,uint256,uint256)': TypedContractEvent<TimingConfigUpdatedEvent.InputTuple, TimingConfigUpdatedEvent.OutputTuple, TimingConfigUpdatedEvent.OutputObject>;
      TimingConfigUpdated: TypedContractEvent<TimingConfigUpdatedEvent.InputTuple, TimingConfigUpdatedEvent.OutputTuple, TimingConfigUpdatedEvent.OutputObject>;
    

      'TreasuryUpdated(address,address)': TypedContractEvent<TreasuryUpdatedEvent.InputTuple, TreasuryUpdatedEvent.OutputTuple, TreasuryUpdatedEvent.OutputObject>;
      TreasuryUpdated: TypedContractEvent<TreasuryUpdatedEvent.InputTuple, TreasuryUpdatedEvent.OutputTuple, TreasuryUpdatedEvent.OutputObject>;
    

      'Unpaused(address)': TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
      Unpaused: TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
    
    };
  }