name: Keeper

on:
  schedule:
    - cron: "*/1 * * * *"
  workflow_dispatch:

jobs:
  run-keeper:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./one-button-hardhat/one-button-hardhat

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install deps
        run: npm install

      - name: Run keeper
        run: node keeper-gh.js
        env:
          CONTRACT_ADDRESS: ${{ secrets.CONTRACT_ADDRESS }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          NETWORK: ${{ secrets.NETWORK }}
          MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
          FUJI_RPC_URL: ${{ secrets.FUJI_RPC_URL }}
